services:
  app:
    build: ./application
    restart: always
    depends_on:
      - db
    volumes:
      - static_data:/app/static
  nginx:
    build: ./nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    volumes:
      - static_data:/app/static
      - type: bind
        source: /var/log/nginx
        target: /var/log/nginx
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
      - type: bind
        source: /var/www/certbot/.well-known/acme-challenge/
        target: /var/www/certbot/.well-known/acme-challenge/
  db:
    image: postgres:17.3
    restart: always
    environment:
      POSTGRES_PASSWORD: '009'
    volumes:
      - postgres_data:/var/lib/postgresql/data/    
volumes:
  static_data:
  postgres_data: